services:
  laravel-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - laravel

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    depends_on:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_HOST: mysql-db
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
      # опционально:
      # PMA_PORT=3306
    networks:
      - laravel

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"

networks:
  laravel:

volumes:
  db_data:
